DROP TABLE Owns;
DROP TABLE Liked;
DROP TABLE Bought;
DROP TABLE ShoppedAt;
DROP TABLE IsSelling;
DROP TABLE Tags;
DROP TABLE Items;
DROP TABLE Shops;
DROP TABLE Users;

DROP TABLE ItemsTrash;
DROP TABLE ShopsTrash;
DROP TABLE UsersTrash;
